name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build portfolio
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: true

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist

      - name: Replace old site with new build
        run: |
          # Remove everything except the .git folder
          find . -maxdepth 1 ! -name '.git' ! -name '.github' -exec rm -rf {} +
          # Move build files from the downloaded artifact to the root
          cp -R dist/* .

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Deploy updated portfolio"
          add: "."
