name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build portfolio
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Check out the gh-pages branch (or the branch you want to deploy to)
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: true

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: temp-dist

      # Clear all existing files in the current directory
      - name: Clear old files
        run: rm -rf *

      # Copy the new build files into the root
      - name: Copy new files
        run: cp -R temp-dist/* .

      - name: Commit and push deployment
        uses: EndBug/add-and-commit@v9
        with:
          message: "Deploy updated portfolio"
          add: "."
